"""
Bybit P2P API Response: get_order_details - детальна інформація про конкретний ордер
Generated: 20250827_011312
Data Description: Detailed information about a specific P2P order
"""

10_order_details_response = {'ext_code': '',
 'ext_info': {},
 'result': {'accountId': '428191401',
            'alternative': '',
            'amount': '3458.00',
            'appealContent': '',
            'appealFlowStatus': '',
            'appealLastSeconds': '0',
            'appealNegotiationNode': 0,
            'appealNickName': '',
            'appealProcessChangeFlag': False,
            'appealSubStatus': '',
            'appealType': 0,
            'appealUserId': '0',
            'appealVersion': 0,
            'appealedTimes': '0',
            'appraiseInfo': {'anonymous': '',
                             'appraiseContent': '',
                             'appraiseId': '',
                             'appraiseType': '',
                             'modifyFlag': '',
                             'updateDate': ''},
            'appraiseShow': [{'appraiseCode': 'GOOD_PRICE',
                              'appraiseType': 'GOOD'},
                             {'appraiseCode': 'TRADE_FAST',
                              'appraiseType': 'GOOD'},
                             {'appraiseCode': 'COURTESY',
                              'appraiseType': 'GOOD'},
                             {'appraiseCode': 'PATIENT',
                              'appraiseType': 'GOOD'},
                             {'appraiseCode': 'SAFE_AND_RELIABLE',
                              'appraiseType': 'GOOD'},
                             {'appraiseCode': 'TRADE_SLOW',
                              'appraiseType': 'BAD'},
                             {'appraiseCode': 'RUDE', 'appraiseType': 'BAD'},
                             {'appraiseCode': 'IMPATIENT',
                              'appraiseType': 'BAD'},
                             {'appraiseCode': 'ADDITIONAL_COSTS',
                              'appraiseType': 'BAD'}],
            'appraiseStatus': 'CANNOT_APPRAISE',
            'beforePrice': '',
            'beforeQuantity': '',
            'beforeToken': '',
            'bulkOrderFlag': False,
            'buyerRealName': 'Bobrowe sprawy Oleksii Pishchuhin ',
            'canAppeal': 'Y',
            'canReport': True,
            'canReportDisagree': False,
            'canReportDisagreeType': [],
            'canReportDisagreeTypes': [],
            'canReportType': [],
            'canReportTypes': [],
            'cancelReason': '',
            'cancelResponsible': '',
            'chainAddress': '',
            'chainTransferLastSeconds': '272',
            'chainType': '',
            'chainWithdrawLastSeconds': '272',
            'completedOrderAppealCount': 0,
            'confirmedPayTerm': {'accountNo': '06102036680000530206358453',
                                 'bankName': '',
                                 'branchName': '',
                                 'businessName': '',
                                 'clabe': '',
                                 'concept': '',
                                 'debitCardNumber': '',
                                 'firstName': '',
                                 'id': '14995815',
                                 'lastName': '',
                                 'mobile': '',
                                 'online': '0',
                                 'payMessage': '',
                                 'paymentConfigVo': {'addTips': '',
                                                     'checkType': 0,
                                                     'itemTips': '',
                                                     'items': [{'label': 'Name',
                                                                'maxLength': '0',
                                                                'name': 'realName',
                                                                'placeholder': 'Please '
                                                                               'Enter '
                                                                               'Name',
                                                                'required': False,
                                                                'type': '',
                                                                'view': False},
                                                               {'label': 'Bank '
                                                                         'Account '
                                                                         'Number',
                                                                'maxLength': '0',
                                                                'name': 'accountNo',
                                                                'placeholder': 'Please '
                                                                               'Enter '
                                                                               'Account '
                                                                               'Number',
                                                                'required': False,
                                                                'type': '',
                                                                'view': False},
                                                               {'label': 'Bank '
                                                                         'Branch',
                                                                'maxLength': '0',
                                                                'name': 'branchName',
                                                                'placeholder': 'Please '
                                                                               'Enter '
                                                                               'Bank '
                                                                               'Branch',
                                                                'required': False,
                                                                'type': '',
                                                                'view': False},
                                                               {'label': 'Bank '
                                                                         'Name',
                                                                'maxLength': '0',
                                                                'name': 'bankName',
                                                                'placeholder': 'Please '
                                                                               'Enter '
                                                                               'Bank '
                                                                               'Name',
                                                                'required': False,
                                                                'type': '',
                                                                'view': False}],
                                                     'online': 0,
                                                     'paymentName': 'PKO Bank',
                                                     'paymentType': '159',
                                                     'sort': 0},
                                 'paymentExt1': '',
                                 'paymentExt2': '',
                                 'paymentExt3': '',
                                 'paymentExt4': '',
                                 'paymentExt5': '',
                                 'paymentExt6': '',
                                 'paymentTemplateVersion': 2,
                                 'paymentType': 159,
                                 'qrcode': '',
                                 'realName': 'VADYM BULAN',
                                 'ruPaymentPrompt': False,
                                 'secondLastName': '',
                                 'visible': 0},
            'contactInfo': [],
            'couponCurrencyAmount': '0.00',
            'couponQuantity': '0',
            'couponTokenId': '',
            'createDate': '1756249366000',
            'currencyId': 'PLN',
            'displayRefund': '0',
            'estimatedGasFee': '0.0000',
            'extension': {'delayTime': '0',
                          'isDelayWithdraw': False,
                          'startTime': ''},
            'fee': '0',
            'fiatBalance': '0',
            'gasFeeTokenId': '',
            'helpType': 'GOING',
            'id': '1960478047544442880',
            'itemId': '1899186728015331328',
            'judgeInfo': {'autoJudgeUnlockTime': '0',
                          'dissentResult': '',
                          'postDissent': '',
                          'preDissent': ''},
            'judgeType': '',
            'loginUserMaskId': 'sa324ea97a0ba480a8ce5079b57430857',
            'makerFee': '',
            'makerUserId': '428191399',
            'middleToken': 'USDT',
            'needSellerExamineCancel': False,
            'nickName': 'ПродамСарай',
            'notifyTokenId': 'USDT',
            'notifyTokenQuantity': '950.0000',
            'onChainInfo': '',
            'orderFinishMinute': 600000,
            'orderSource': 'P2P',
            'orderType': 'ORIGIN',
            'payCode': '361718',
            'payerRealName': '',
            'paymentTermList': [{'accountNo': '06102036680000530206358453',
                                 'bankName': '',
                                 'branchName': '',
                                 'businessName': '',
                                 'clabe': '',
                                 'concept': '',
                                 'debitCardNumber': '',
                                 'firstName': '',
                                 'id': '14995815',
                                 'lastName': '',
                                 'mobile': '',
                                 'online': '0',
                                 'payMessage': '',
                                 'paymentConfigVo': {'addTips': '',
                                                     'checkType': 0,
                                                     'itemTips': '',
                                                     'items': [{'label': 'Name',
                                                                'maxLength': '0',
                                                                'name': 'realName',
                                                                'placeholder': 'Please '
                                                                               'Enter '
                                                                               'Name',
                                                                'required': False,
                                                                'type': '',
                                                                'view': False},
                                                               {'label': 'Bank '
                                                                         'Account '
                                                                         'Number',
                                                                'maxLength': '0',
                                                                'name': 'accountNo',
                                                                'placeholder': 'Please '
                                                                               'Enter '
                                                                               'Account '
                                                                               'Number',
                                                                'required': False,
                                                                'type': '',
                                                                'view': False},
                                                               {'label': 'Bank '
                                                                         'Branch',
                                                                'maxLength': '0',
                                                                'name': 'branchName',
                                                                'placeholder': 'Please '
                                                                               'Enter '
                                                                               'Bank '
                                                                               'Branch',
                                                                'required': False,
                                                                'type': '',
                                                                'view': False},
                                                               {'label': 'Bank '
                                                                         'Name',
                                                                'maxLength': '0',
                                                                'name': 'bankName',
                                                                'placeholder': 'Please '
                                                                               'Enter '
                                                                               'Bank '
                                                                               'Name',
                                                                'required': False,
                                                                'type': '',
                                                                'view': False}],
                                                     'online': 0,
                                                     'paymentName': 'PKO Bank',
                                                     'paymentType': '159',
                                                     'sort': 0},
                                 'paymentExt1': '',
                                 'paymentExt2': '',
                                 'paymentExt3': '',
                                 'paymentExt4': '',
                                 'paymentExt5': '',
                                 'paymentExt6': '',
                                 'paymentTemplateVersion': 2,
                                 'paymentType': 159,
                                 'qrcode': '',
                                 'realName': 'VADYM BULAN',
                                 'ruPaymentPrompt': False,
                                 'secondLastName': '',
                                 'visible': 0}],
            'paymentTermResult': {'accountNo': '',
                                  'bankName': '',
                                  'branchName': '',
                                  'businessName': '',
                                  'clabe': '',
                                  'concept': '',
                                  'debitCardNumber': '',
                                  'firstName': '',
                                  'id': '0',
                                  'lastName': '',
                                  'mobile': '',
                                  'online': '',
                                  'payMessage': '',
                                  'paymentConfigVo': {'addTips': '',
                                                      'checkType': 0,
                                                      'itemTips': '',
                                                      'items': [],
                                                      'online': 0,
                                                      'paymentName': '',
                                                      'paymentType': '0',
                                                      'sort': 0},
                                  'paymentExt1': '',
                                  'paymentExt2': '',
                                  'paymentExt3': '',
                                  'paymentExt4': '',
                                  'paymentExt5': '',
                                  'paymentExt6': '',
                                  'paymentTemplateVersion': 0,
                                  'paymentType': 0,
                                  'qrcode': '',
                                  'realName': '',
                                  'ruPaymentPrompt': False,
                                  'secondLastName': '',
                                  'visible': 0},
            'paymentType': 159,
            'price': '3.64',
            'proofDownloadFlag': False,
            'quantity': '950.0000',
            'realOrderStatus': 20,
            'recentExecuteRate': 50,
            'recentOrderNum': 7,
            'remark': '- Wysyłam TYLKO ze swojego KONTA, z MOIM imieniem i '
                      'nazwiskiem❇️ 781 972 552\n'
                      '‼️nie ma blik , tu mam PKO\n'
                      '\n'
                      'Witaj! Aby przelew został zrealizowany, WYMAGANE są '
                      'WSZYSTKIE dane: (nie coś jedno) \n'
                      '- imię i nazwisko (ŁACINKĄ)‼️\n'
                      '- numer telefonu \n'
                      '- numer RACHUNKU bankowego (NIE numer karty!)‼️\n'
                      '\n'
                      '\n'
                      'DANE odbiorcy muszą zgadzać się z danymi z konta '
                      'BYBIT  \n'
                      'NIE wysyłam do OSÓB TRZECICH (znajomi, rodzina, '
                      'partnerzy itd.)⛔️\n'
                      '\n'
                      'BRAK któregokolwiek z tych danych = BRAK przelewu\n'
                      'Nie wysyłam pieniędzy, jeśli nie otrzymam KOMPLETU '
                      'informacji\n'
                      '\n'
                      'Anulowanie zlecenia tylko przez APELACJĘ — kilka DNI\n'
                      'Wciśnij „RELEASE CRYPTO” w Bybit natychmiast po '
                      'otrzymaniu przelewu          #q #p',
            'selfUnreadMsgCount': '0',
            'sellerCancelExamineRemainTime': '',
            'sellerRealName': 'VADYM BULAN',
            'showContact': False,
            'showPaymentList': True,
            'side': 0,
            'status': 20,
            'takerFee': '',
            'targetAccountId': '47658711',
            'targetConnectInformation': '',
            'targetFirstName': '',
            'targetNickName': 'User8709810b686',
            'targetSecondName': '',
            'targetUserAuthStatus': 2,
            'targetUserDisplays': [],
            'targetUserId': '47658709', // це uid контрагента
            'targetUserMaskId': 'sc3e64a82d19043d2a6be57c948002568',
            'targetUserType': 'PERSONAL',
            'tokenBalance': '3824.412700000000000000',
            'tokenId': 'USDT',
            'tokenName': 'USDT',
            'totalAppealTimes': '2',
            'totalCompletedOrderAppealCount': 3,
            'totalCurrencyAmount': '3458.00',
            'tradeHashCode': '',
            'tradingFeeTokenId': '',
            'transactionId': '0',
            'transferDate': '1756249381000',
            'transferLastSeconds': '0',
            'unreadMsgCount': '0',
            'updateDate': '1756249381000',
            'usedCoupon': False,
            'userId': '428191399',
            'verificationOrder': False,
            'verificationOrderLastSeconds': '0'},
 'ret_code': 0,
 'ret_msg': 'SUCCESS',
 'time_now': '1756249993.226828'}
