UA:
  - АДРІАН
  - АЛІСТЕР
  - АНАТОЛІЙ
  - ANATOLII
  - ANATOLIY
  - АНДРІАН
  - АНДРІЙ
  - ANDRII
  - ANDRIY
  - АНТІН
  - ANTIN
  - АНТОНІЙ
  - ANTONII
  - АРСЕНІЙ
  - ARSENII
  - BOHDAN
  - БОГУСЛАВ
  - BOHUSLAV
  - BORYS
  - БОРИСЛАВ
  - BORYSLAV
  - БРОНІСЛАВ
  - BRONISLAV
  - В'ЯЧЕСЛАВ
  - V'YACHESLAV
  - VYACHESLAV
  - VIACHESLAV
  - VADYM
  - VALENTYN
  - ВАЛЕРІЙ
  - ВАРФОЛОМІЙ
  - VARFOLOMII
  - ВАСИЛЬ
  - VASYL
  - ВЕНІАМІН
  - VENIAMIN
  - ВІКТОР
  - ВІТАЛІЙ
  - VLADYSLAV
  - ВОЛОДИМИР
  - VOLODYMYR
  - ГАВРИЛО
  - HAVRYLO
  - ГЕННАДІЙ
  - HENNADII
  - HENNADIY
  - ГЕОРГІЙ
  - HERASYM
  - ГЕРВАСІЙ
  - HERVASII
  - ГЕРМАН
  - HERMAN
  - ГЛІБ
  - HLIB
  - ГНАТ
  - HNAT
  - ГОРДІЙ
  - HORDII
  - ГРИГІР
  - HRYHIR
  - ГРИГОРІЙ
  - HRYHORII
  - HRYHORIY
  - GRYGORIY
  - GRYGORII
  - DAVYD
  - ДАНИЛО
  - DANYLO
  - DANYIL
  - DENYS
  - ДМИТРО
  - DMYTRO
  - ЕДВАРД
  - EDVARD
  - ЕДУАРД
  - EDUARD
  - ЕЛВІН
  - ELVIN
  - ЕНЕЙ
  - ENEY
  - ЄВГЕН
  - YEVHEN
  - ЄВГЕНІЙ
  - YEVHENII
  - YEVHENIY
  - ЄГОР
  - YEHOR
  - ЄЛИСЕЙ
  - YELYSEY
  - ЗАХАРІЙ
  - ZAKHARII
  - ЗИНОВІЙ
  - ZYNOVII
  - ЗІНОВІЙ
  - ZINOVII
  - ЗОРЕСЛАВ
  - ZORESLAV
  - ЗОРЯН
  - ZORYAN
  - ІГОР
  - IHOR
  - ІЗМАЇЛ
  - IZMAYIL
  - ІЗРАЇЛЬ
  - IZRAYIL
  - ІЗЯСЛАВ
  - IZYASLAV
  - ІЛАРІОН
  - ILARION
  - ІЛЛЯ
  - ILLIA
  - ІЛЬКО
  - ILKO
  - ЙОСИП
  - YOSYP
  - КИРИЛО
  - KYRYLO
  - КЛИМ
  - KLYM
  - КОСТЯНТИН
  - KOSTYANTYN
  - KOSTIANTYN
  - ЛАВРЕНТІЙ
  - LAVRENTII
  - ЛАЗАР
  - LAZAR
  - ЛЕВКО
  - LEVKO
  - ЛЕОНІД
  - LEONID
  - ЛЕОНТІЙ
  - LEONTII
  - ЛУК'ЯН
  - LUK'YAN
  - LUKYAN
  - LUKIAN
  - MAKSYM
  - МАР'ЯН
  - MAR'YAN
  - MARYAN
  - MARIAN
  - МАРКІЯН
  - MARKIYAN
  - MARKIAN
  - МАРКО
  - MARKO
  - МАРТИН
  - MARTYN
  - МАТВІЙ
  - MATVII
  - МЕЛЕТІЙ
  - MELETII
  - МИКИТА
  - MYKYTA
  - МИКОЛА
  - MYKOLA
  - MYKOLAI
  - МИКОЛАЙ
  - MYKOLAY
  - MYRON
  - MYROSLAV
  - МИХАЙЛО
  - MYKHAYLO
  - MYKHAILO
  - МСТИСЛАВ
  - MSTYSLAV
  - НАЗАР
  - NAZAR
  - НАЗАРІЙ
  - NAZARII
  - НЕСТОР
  - NESTOR
  - НИКИФОР
  - NYKYFOR
  - MYKYFOR
  - НИЧИПІР
  - NYCHYPIR
  - НІКІТА
  - OLEH
  - ОЛЕКСА
  - OLEKSA
  - ОЛЕКСАНДР
  - OLEKSANDR
  - ОЛЕКСІЙ
  - OLEKSII
  - ОЛЕСЬ
  - OLES
  - ОПАНАС
  - OPANAS
  - ОРЕСТ
  - OREST
  - ОСТАП
  - OSTAP
  - ПАВЛО
  - PAVLO
  - ПАНАС
  - PANAS
  - ПЕТРО
  - PETRO
  - ПИЛИП
  - PYLYP
  - ПРОКІП
  - PROKIP
  - РОСТИСЛАВ
  - ROSTYSLAV
  - САВА
  - SAVA
  - САВВА
  - SAVVA
  - САВКО
  - SAVKO
  - САМІЙЛО
  - SAMIYLO
  - СВЯТОСЛАВ
  - SVYATOSLAV
  - SVIATOSLAV
  - СЕВЕРИН
  - SEVERYN
  - СЕРГІЙ
  - SERHII
  - SERGII
  - SERGIY
  - СИМОН
  - SYMON
  - СТАНІСЛАВ
  - СТЕПАН
  - STEPAN
  - ТАРАС
  - TARAS
  - ТИМІШ
  - TYMISH
  - ТИМОФІЙ
  - TYMOFII
  - TYMOFIY
  - ТИХОН
  - TYKHON
  - ТРОХИМ
  - TROKHYM
  - ФЕДІР
  - FEDIR
  - ФРАНЦИСК
  - FRANTSYSK
  - ХАРИТОН
  - KHARYTON
  - ХОМА
  - KHOMA
  - ХРИСТОФОР
  - KHRYSTOFOR
  - ЧІПКА
  - CHIPKA
  - ЮЛІЙ
  - YULII
  - ЮРІЙ
  - YURII
  - ЮРКО
  - YURKO
  - ЮСТИН
  - YUSTYN
  - ЮХИМ
  - YUKHYM
  - ЯКІВ
  - YAKIV
  - ЯРЕМА
  - YAREMA
  - ЯРОСЛАВ
  - YAROSLAV

  - АГАФІЯ
  - AHAFIIA
  - АЛІНА
  - АЛЬОНА
  - АНАСТАСІЯ
  - ANASTASIIA
  - АНАТОЛІЯ
  - ANATOLIIA
  - АНГЕЛІНА
  - ANHELINA
  - АНЖЕЛІКА
  - АНТОНІНА
  - ANTONINA
  - АРІАНА
  - ARIANA
  - БОГДАНА
  - BOHDANA
  - БРОНІСЛАВА
  - BRONISLAVA
  - В'ЯЧЕСЛАВА
  - V'YACHESLAVA
  - ВАЛЕНТИНА
  - VALENTYNA
  - ВАЛЕРІЯ
  - VALERIIA
  - ВЕРОНІКА
  - ВІКТОРІЯ
  - VIKTORIIA
  - ВІРА
  - VIRA
  - ВЛАДИСЛАВА
  - VLADYSLAVA
  - ГАЛИНА
  - HALYNA
  - ГАННА
  - ДАР'Я
  - ДАРІЯ
  - DARIIA
  - ДАРИНА
  - DARYNA
  - ДЗВЕНИСЛАВА
  - DZVENYSLAVA
  - ДІАНА
  - ДОМІНІКА
  - ЕДІТА
  - ЕМІЛІЯ
  - EMILIIA
  - ЄВА
  - YEVA
  - ЄВГЕНІЯ
  - YEVHENIIA
  - ЄВДОКІЯ
  - YEVDOKIIA
  - ЄЛИЗАВЕТА
  - YELYZAVETA
  - ЗЕМФІРА
  - ZEMFIRA
  - ЗИНОВІЯ
  - ZYNOVIIA
  - ЗІНОВІЯ
  - ZINOVIIA
  - ЗОРЕСЛАВА
  - ZORESLAVA
  - ЗОРЯНА
  - ZORYANA
  - ZORIANA
  - ІВАННА
  - IVANNA
  - ІЛОНА
  - ІННА
  - ІРИНА
  - IRYNA
  - ЙОСИПА
  - YOSYPA
  - КАМІЛА
  - КАТЕРИНА
  - KATERYNA
  - КЛАВДІЯ
  - KLAVDIIA
  - LARYSA
  - ЛІДІЯ
  - LIDIIA
  - ЛІЛІЯ
  - LILIIA
  - ЛУКІЯ
  - LUKIIA
  - ЛЮБОВ
  - ЛЮДМИЛА
  - LYUDMYLA
  - LIUDMYLA
  - МАЙЯ
  - MAYYA
  - MAIIA
  - МАР'ЯНА
  - MAR'YANA
  - MARIANA
  - MARYANA
  - МАРИНА
  - MARYNA
  - МАРІЧКА
  - MARICHKA
  - МАРІЯ
  - MARIIA
  - МЕЛАНІЯ
  - MELANIIA
  - МИРОСЛАВА
  - MYROSLAVA
  - НАДІЯ
  - NADIIA
  - НАТАЛІЯ
  - NATALIIA
  - НАТАЛЯ
  - НІКА
  - НІНА
  - ОКСАНА
  - OKSANA
  - ОЛЕКСАНДРА
  - OLEKSANDRA
  - ОЛЕНА
  - OLENA
  - ОЛЕСЯ
  - ОЛІМПІАДА
  - OLIMPIADA
  - OLHA
  - ПАРАСКОВІЯ
  - PARASKOVIIA
  - ПОЛІНА
  - POLINA
  - РАЇСА
  - RAYISA
  - РОКСОЛАНА
  - ROKSOLANA
  - РОСТИСЛАВА
  - ROSTYSLAVA
  - РУСЛАНА
  - RUSLANA
  - СВІТЛАНА
  - SVITLANA
  - СВЯТОСЛАВА
  - SVYATOSLAVA
  - СОЛОМІЯ
  - SOLOMIIA
  - СОФІЯ
  - SOFIIA
  - СТАНІСЛАВА
  - STANISLAVA
  - СТЕПАНІЯ
  - STEPANIIA
  - СТЕФАНІЯ
  - STEFANIIA
  - ТАЇСІЯ
  - TAYISIIA
  - ТЕТЯНА
  - TETYANA
  - TETIANA
  - ФЕЛІКСА
  - FELIKSA
  - ХРИСТИНА
  - KHRYSTYNA
  - KRYSTYNA
  - ЮЛІЯ
  - YULIIA
  - ЮНОНА
  - YUNONA
  - ЮСТИНА
  - YUSTYNA
  - ЯНІНА
  - ЯРИНА
  - YARYNA
  - ЯРОСЛАВА
  - YAROSLAVA

BY:
  - ALEH
  - ALIAKSANDAR
  - ALIAKSANDR
  - ALIAKSEI
  - ANATOLII
  - ANISIM
  - ARKADZII
  - ARTSIOM
  - AFANASII
  - BAHDAN
  - BAHUSLAU
  - BARYS
  - BRANISLAU
  - VADZIM
  - VALERYI
  - VALIANTSIN
  - VASIL
  - VIENIADZIKT
  - VIKENTSII
  - VIKTAR
  - VITAUT
  - VIACHASLAU
  - HARDEI
  - HAURYLA
  - HENADZII
  - HENADZ
  - HLEB
  - DAMINIK
  - DAUHIERD
  - DZMITRYI
  - DZMITRI
  - DZMITRY
  - DZIANIS
  - IHAR
  - IHNAT
  - KANDRAT
  - KANSTANTSIN
  - KIRYL
  - KUZMA
  - LAURENTSII
  - LEANID
  - MATSVEI
  - MIKALAI
  - MIKITA
  - MSTISLAU
  - PRAKOFII
  - PIATRO
  - RADZIVON
  - RAMAN
  - RASTISLAU
  - RYHOR
  - STANISLAU
  - STSIAPAN
  - SIAMION
  - SIARHEI
  - ULADZIMIER
  - ULADZISLAU
  - FIODAR
  - FRANTSYISK
  - TSIMAFEI
  - TSIKHAN
  - IURYI
  - YAHOR
  - YAKAU
  - JANKA
  - YARASLAU
  - YAUHEN
  - YAUHENII
  - YAUHENIY
  - YAUHENI
  - YAFIM

  - ADELIAIDA
  - ALIAKSANDRA
  - ANASTASIYA
  - ANZHALIKA
  - ANTANINA
  - AUDOTSIA
  - BRANISLAVA
  - VIKTORYIA
  - VIJALETA
  - VIALETA
  - VIALETTA
  - VOLHA
  - VOLIA
  - DAMINIKA
  - EUDAKIIA
  - ZEMFIRA
  - IRENA
  - KARALINA
  - KACIARYNA
  - KHRYSTSINA
  - LIDZIYA
  - LIZAVETA
  - MAHDALENA
  - MARGARYTA
  - MARYIA
  - PALINA
  - SVIATLANA
  - SAFIA
  - TATSIANA
  - YADVIHA
  - YAUHENIIA
  - YAUHENIA
  - YAUHENIYA

PL:
  - ALBIN
  - ALOJZY
  - ALVIN
  - AMADEUSZ
  - ANDRZEJ
  - ANICET
  - ANTEK
  - ANTONI
  - ANTOS
  - APOLINARY
  - ARKADIUSZ
  - ARKADY
  - BARDIL
  - BARNIM
  - BARTEK
  - BARTŁOMIEJ
  - BARTLOMIEJ
  - BARTOSZ
  - BAZYLI
  - BEREK
  - BLAŽEJ
  - BLAZEJ
  - BOGOMIL
  - BOGUSŁAW
  - BOGUSLAW
  - BOHDAN
  - BOLESŁAW
  - BOLESAW
  - BORZYSŁAW
  - BORZYSLAW
  - BOYAN
  - BRONISŁAW
  - BRONISLAW
  - BRUNO
  - BRUNON
  - CASIMIR
  - CELESTYN
  - CEZARY
  - CTIRAD
  - CZESŁAW
  - CZESLAW
  - DANIEL
  - DARIO
  - DARIUSZ
  - DAWID
  - DOBIESŁAW
  - DOBIESLAW
  - DOBROGOST
  - ELIGIUSZ
  - ERNEST
  - ERYK
  - FELIKS
  - FERDYNAND
  - FLORIAN
  - FRANCISZEK
  - FRYDERYK
  - GERARD
  - GODZIMIR
  - GRZEGORZ
  - HENRYK
  - HERBERT
  - HERMAN
  - HIERONIM
  - HUBERT
  - IGNACY
  - IRENEUSZ
  - JACEK
  - JAKUB
  - JAN
  - JANEK
  - JANISŁAW
  - JANISLAW
  - JANUSZ
  - JAREK
  - JAROMIR
  - JAROSŁAW
  - JAROSLAW
  - JĘDRZEJ
  - JEDRZEJ
  - JEREMI
  - JERZY
  - JOZEF
  - JULIUSZ
  - JURAND
  - JUREK
  - KACPER
  - KAMIL
  - KAROL
  - KLEMENS
  - KOSTEK
  - KRYSTIAN
  - KRZESIMIR
  - KRZYSZTOF
  - KSAWERY
  - LECH
  - LEOPOLD
  - LESZEK
  - LOTAR
  - LUBOMIR
  - LUCJAN
  - LUDOMIR
  - LUDWIK
  - ŁUKASZ
  - LUKASZ
  - MACIEJ
  - MACIUŚ
  - MACIUS
  - MAIK
  - MAKSYMILIAN
  - MANUEL
  - MARCIN
  - MAREK
  - MARIUSZ
  - MATEUSZ
  - MAURYCY
  - MICHAŁ
  - MICHAL
  - MIECZYSŁAW
  - MIECZYSLAW
  - MIESZKO
  - MIKOŁAJ
  - MIKOLAJ
  - MILAN
  - MILOŠ
  - MILOS
  - MIROSŁAW
  - MORDECHAJ
  - MŚCIWÓJ
  - MSCIWOJ
  - NORBERT
  - ODOLAN
  - OLGIERD
  - PATRYK
  - PAWEŁ
  - PAWEL
  - PIOTR
  - PRZEMYSŁ
  - PRZEMYSL
  - PRZEMYSŁAW
  - PRZEMYSLAW
  - PRZYBYSŁAW
  - PRZYBYSLAW
  - RADOSŁAW
  - RADOSLAW
  - RAFAŁ
  - RAFAL
  - RAJMUND
  - RATIBOR
  - RATIMIR
  - ROMUALD
  - RYSZARD
  - SAMUEL
  - SEWERYN
  - SŁAWOJ
  - SLAWOJ
  - SŁAWOMIR
  - SLAWOMIR
  - SŁAWOSZ
  - SLAWOSZ
  - SOBIESLAW
  - SPYCIMIR
  - SPYTEK
  - STEFAN
  - ŚWIĘTOPEŁK
  - SWIETOPELK
  - ŚWIĘTOSŁAW
  - SWIETOSLAW
  - SYLWESTER
  - SZCZEPAN
  - SZLAMA
  - SZLOMO
  - SZMUEL
  - SZMUL
  - SZYMON
  - TADEUSZ
  - TEODOR
  - TEOFIL
  - TOMASZ
  - TOMEK
  - TYTUS
  - WACŁAW
  - WACLAW
  - WALDEMAR
  - WALENTY
  - WALERIAN
  - WALERY
  - WAWRZYNIEC
  - WIELIMIR
  - WIESŁAW
  - WIESLAW
  - WIKTOR
  - WITOLD
  - WŁADYSŁAW
  - WALDYSLAW
  - WŁODZIMIERZ
  - WLODZIMIERZ
  - WOJCIECH
  - ZAWISZA
  - ZBIGNIEW
  - ZBYLUT
  - ZBYSZKO
  - ZDZISŁAW
  - ZDZISLAW
  - ZIEMOWIT
  - ZYGMUNT

  - ADRIANA
  - AGATA
  - AGNIESZKA
  - ANDREA
  - ANGELIKA
  - ANIELA
  - ANKA
  - BARBARA
  - BASIA
  - BEATA
  - BIANKA
  - BOGNA
  - BOŻENA
  - BOZENA
  - BRONISŁAWA
  - DAGMARA
  - DANUTA
  - DOBRONIEGA
  - DOMINIKA
  - DONKA
  - EDYTA
  - ELISA
  - ELZBIETA
  - EWA
  - FRANCISZKA
  - GISELA
  - GOŁDA
  - GOLDA
  - GRAŻYNA
  - GRAZYNA
  - HELENA
  - IRENA
  - IRMA
  - IWONA
  - IZABELLA
  - IZOLDA
  - JADWIGA
  - JAGNA
  - JAGODA
  - JANINA
  - JARMILA
  - JOANNA
  - JOLANTA
  - JULIA
  - JUSTYNA
  - KAJA
  - KALINA
  - KAROLINA
  - KASIA
  - KATARZYNA
  - KLAUDIA
  - KORNELIA
  - LAURA
  - LUDWIKA
  - LUIZA
  - MAGDALENA
  - MAŁGORZATA
  - MALGORZATA
  - MAŁGOSIA
  - MAGOSIA
  - MARTA
  - MARZENA
  - MELANIA
  - MIROSŁAWA
  - MONIKA
  - NAWOJA
  - NIKOLINA
  - OLIWIA
  - PAULA
  - PAULINA
  - RENATA
  - RICHEZA
  - ROMANA
  - SABINA
  - TEKLA
  - TEOFILA
  - TERESA
  - TOSIA
  - URSZULA
  - WANDA
  - WIESŁAWA
  - WIESLAWA
  - WŁADYSŁAWA
  - WADYSLAWA
  - ZOFIA
  - ZOSIA
  - ZOŚKA
  - ZOSKA
